
GET http://localhost:1337/status/
Accept: application/json

###


POST http://localhost:1337/software/1a799cb1-6f18-4b69-8bb5-41f18cf32269/issues
Content-Type: application/json

{
  "description": "Dang Thing Don't Work",
  "impact": "Inconvenience"
}
